### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by elliotthilaire** [ArtS/28degrees-export#15]
Thanks for making this.

The last few times I've tried using it I have been getting:
```
Logging in...
Traceback (most recent call last):
  File "./export.py", line 315, in <module>
    export(**vars(args))
  File "./export.py", line 227, in export
    br = login(creds)
  File "./export.py", line 30, in wrapped
    r = f(*args, **kwargs)
  File "./export.py", line 129, in login
    br.open('https://28degrees-online.latitudefinancial.com.au/')
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 203, in open
    return self._mech_open(url, data, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/mechanize/_mechanize.py", line 255, in _mech_open
    raise response
mechanize._response.httperror_seek_wrapper: HTTP Error 400: Bad Request
```

I suspect the site may have changed. If it's not just me I'll dig into it deeper.

Is anyone else getting this error too?

**Comment by elliotthilaire** [comment]
This has resolved itself. It worked when I tried for this months transactions.
