### ISSUE TITLE
Script will fail if there is not enough transactions present for a Next button

### ISSUE THREAD

**Issue by elliotthilaire** [ArtS/28degrees-export#18]
I've started using my 28 degrees card again after a while. I have enough transactions that manually copying the details is a pain but not enough to overflow onto a second page.

The script fails because it goes looking for the next button which is not present:
```
NoSuchElementException: Message: no such element: Unable to locate element: {"method":"name","selector":"nextButton"}
```

A suitable work around to this problem for now is to spend more money and try again later. 🤑

Full trace below:
```
Traceback (most recent call last):
  File "./export.py", line 255, in <module>
    export(**vars(args))
  File "./export.py", line 179, in export
    driver = login(creds)
  File "./export.py", line 78, in login
    nextBtn = get_next_btn(driver)
  File "./export.py", line 56, in get_next_btn
    return browser.find_element_by_name('nextButton')
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 858, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"name","selector":"nextButton"}
  (Session info: chrome=71.0.3578.98)
  (Driver info: chromedriver=2.37.544337 (8c0344a12e552148c185f7d5117db1f28d6c9e85),platform=Mac OS X 10.14.2 x86_64)
```

**Comment by ArtS** [comment]
@elliotthilaire can you please test this https://github.com/ArtS/28degrees-export/pull/19

**Comment by elliotthilaire** [comment]
@ArtS Thanks. I will test this within the next few days.

**Comment by elliotthilaire** [comment]
@ArtS I've left a PR that fixes this now. Is there anything else you'd like before you can merge?

**Comment by ArtS** [comment]
Brilliant, thanks!!!
